language: php

# add PHP versions
php:
  - 5.3

# - PHPUnit
script: phpunit --colors --coverage-text

# http://about.travis-ci.org/docs/user/languages/php/
# http://about.travis-ci.org/docs/user/ci-environment/
